import type { Locale } from "./i18n";

const en = {
  intake: {
    deleted: "Mission deleted. ActionOS will take no further action.", recipe: "Live recipe · company follow-up", title: "Give ActionOS the messy version.", scope: "Describe it, paste the message, attach the proof—or combine them. Gemini will organize it.", prompt: "What happened, and what are you waiting for?", placeholder: "Example: The store promised to refund $59 for order 1842 by Friday…", addFile: "+ Add screenshot, photo, or PDF", working: "Working…", build: "Build my plan →", ai: "Google’s Gemini service reads only what you submit to extract a draft. It has no contact tools and cannot approve, send, or mark the mission done.", data: "Data and retention details", ready: "ready to analyze", remove: "Remove", combined: "✓ Text and file will be analyzed together", common: "Or start with a common situation", after: "What happens after I approve?", after1: "ActionOS sends the one follow-up you approved.", after2: "It rejects acknowledgements that do not prove the result.", after3: "Your durable mission page records every decision and supported result.", adapter: "The accelerated demo uses a controlled adapter. A controlled email pilot is available only for reviewed, allowlisted recipients.", reading: "Gemini is reading your evidence", extracting: "Extracting the outcome, responsible party, dates, and proof requirements.", complex: "Still working — complex or ambiguous evidence can take a little longer.", slow: "This is taking longer than usual. Nothing has been sent to the company.", elapsed: "elapsed · usually 10–25 seconds", privacy: "ActionOS processes only what you share. Raw-source retention ends within 24 hours. No external action happens before you review and activate a versioned plan.", privacyLink: "Privacy details", srInitial: "Gemini is analyzing the evidence. This usually takes 10 to 25 seconds.", srComplex: "The analysis is still working on complex or ambiguous evidence.", srSlow: "The analysis is taking longer than usual. Nothing has been sent to the company."
  },
  analysis: {
    stages: ["Evidence secured", "Gemini is reading the promise", "Checking dates, amounts and proof", "Review ready"], stopped: "Analysis stopped. You can try again.", saved: "Saved and running in the background", failedTitle: "ActionOS could not finish the analysis.", building: "Building your follow-up plan…", failedText: "Nothing was sent. Your private source is still available for a bounded retry.", running: "You can close this page. ActionOS will keep the job and reopen the review when it is ready.", attempt: "Bounded attempt", of: "of 3", retentionBefore: "Raw-source retention ends", retentionAfter: "Deletion processing may be asynchronous.", restarting: "Restarting…", retry: "Try analysis again", refresh: "ActionOS could not refresh this saved job. Retrying automatically."
  }
};

type InteractiveCopy = typeof en;
const es: InteractiveCopy = {
  intake: { deleted: "Caso eliminado. ActionOS no realizará más acciones.", recipe: "Flujo activo · seguimiento empresarial", title: "Dale a ActionOS la versión desordenada.", scope: "Describilo, pegá el mensaje, adjuntá la prueba o combiná todo. Gemini lo organizará.", prompt: "¿Qué ocurrió y qué estás esperando?", placeholder: "Ejemplo: La tienda prometió devolver USD 59 del pedido 1842 antes del viernes…", addFile: "+ Agregar captura, foto o PDF", working: "Procesando…", build: "Crear mi plan →", ai: "El servicio Gemini de Google lee únicamente lo que enviás para extraer un borrador. No tiene herramientas de contacto y no puede aprobar, enviar ni marcar el caso como terminado.", data: "Datos y retención", ready: "listo para analizar", remove: "Quitar", combined: "✓ El texto y el archivo se analizarán juntos", common: "O empezá con una situación habitual", after: "¿Qué sucede después de aprobar?", after1: "ActionOS envía el único seguimiento que aprobaste.", after2: "Rechaza acuses de recibo que no prueban el resultado.", after3: "La página durable del caso registra cada decisión y resultado respaldado.", adapter: "La demo acelerada utiliza un adaptador controlado. El piloto de correo sólo está disponible para destinatarios revisados y permitidos.", reading: "Gemini está leyendo tu evidencia", extracting: "Extrayendo resultado, responsable, fechas y requisitos de prueba.", complex: "Sigue trabajando: la evidencia compleja o ambigua puede demorar un poco más.", slow: "Está tardando más de lo habitual. No se envió nada a la empresa.", elapsed: "transcurridos · normalmente 10–25 segundos", privacy: "ActionOS procesa únicamente lo que compartís. La retención de la fuente termina dentro de 24 horas. No ocurre ninguna acción externa antes de que revises y actives un plan versionado.", privacyLink: "Detalles de privacidad", srInitial: "Gemini está analizando la evidencia. Normalmente demora entre 10 y 25 segundos.", srComplex: "El análisis continúa trabajando con evidencia compleja o ambigua.", srSlow: "El análisis está tardando más de lo habitual. No se envió nada a la empresa." },
  analysis: { stages: ["Evidencia protegida", "Gemini está leyendo la promesa", "Verificando fechas, montos y prueba", "Revisión lista"], stopped: "El análisis se detuvo. Podés intentarlo nuevamente.", saved: "Guardado y ejecutándose en segundo plano", failedTitle: "ActionOS no pudo terminar el análisis.", building: "Creando tu plan de seguimiento…", failedText: "No se envió nada. Tu fuente privada sigue disponible para un reintento limitado.", running: "Podés cerrar esta página. ActionOS conservará el trabajo y abrirá la revisión cuando esté lista.", attempt: "Intento limitado", of: "de 3", retentionBefore: "La retención de la fuente termina", retentionAfter: "El procesamiento de eliminación puede ser asincrónico.", restarting: "Reiniciando…", retry: "Intentar el análisis nuevamente", refresh: "ActionOS no pudo actualizar este trabajo guardado. Reintentará automáticamente." }
};
const pt: InteractiveCopy = {
  intake: { deleted: "Caso excluído. O ActionOS não realizará mais ações.", recipe: "Fluxo ativo · acompanhamento empresarial", title: "Envie ao ActionOS a versão desorganizada.", scope: "Descreva, cole a mensagem, anexe a prova ou combine tudo. O Gemini organizará.", prompt: "O que aconteceu e o que você está esperando?", placeholder: "Exemplo: A loja prometeu devolver US$ 59 do pedido 1842 até sexta-feira…", addFile: "+ Adicionar captura, foto ou PDF", working: "Processando…", build: "Criar meu plano →", ai: "O serviço Gemini do Google lê somente o que você envia para extrair um rascunho. Ele não possui ferramentas de contato e não pode aprovar, enviar nem marcar o caso como concluído.", data: "Dados e retenção", ready: "pronto para analisar", remove: "Remover", combined: "✓ O texto e o arquivo serão analisados juntos", common: "Ou comece com uma situação comum", after: "O que acontece depois da aprovação?", after1: "O ActionOS envia o único acompanhamento que você aprovou.", after2: "Rejeita confirmações que não comprovam o resultado.", after3: "A página durável do caso registra cada decisão e resultado comprovado.", adapter: "A demonstração acelerada usa um adaptador controlado. O piloto de e-mail está disponível apenas para destinatários revisados e permitidos.", reading: "O Gemini está lendo sua evidência", extracting: "Extraindo resultado, responsável, datas e requisitos de prova.", complex: "Ainda trabalhando — evidências complexas ou ambíguas podem demorar um pouco mais.", slow: "Está demorando mais que o normal. Nada foi enviado à empresa.", elapsed: "decorridos · normalmente 10–25 segundos", privacy: "O ActionOS processa somente o que você compartilha. A retenção da fonte termina em até 24 horas. Nenhuma ação externa ocorre antes de você revisar e ativar um plano versionado.", privacyLink: "Detalhes de privacidade", srInitial: "O Gemini está analisando a evidência. Isso normalmente leva de 10 a 25 segundos.", srComplex: "A análise continua trabalhando com evidências complexas ou ambíguas.", srSlow: "A análise está demorando mais que o normal. Nada foi enviado à empresa." },
  analysis: { stages: ["Evidência protegida", "Gemini está lendo a promessa", "Verificando datas, valores e prova", "Revisão pronta"], stopped: "A análise parou. Você pode tentar novamente.", saved: "Salvo e executando em segundo plano", failedTitle: "O ActionOS não conseguiu concluir a análise.", building: "Criando seu plano de acompanhamento…", failedText: "Nada foi enviado. Sua fonte privada continua disponível para uma nova tentativa limitada.", running: "Você pode fechar esta página. O ActionOS manterá o trabalho e abrirá a revisão quando estiver pronta.", attempt: "Tentativa limitada", of: "de 3", retentionBefore: "A retenção da fonte termina", retentionAfter: "O processamento da exclusão pode ser assíncrono.", restarting: "Reiniciando…", retry: "Tentar a análise novamente", refresh: "O ActionOS não conseguiu atualizar este trabalho salvo. Tentará novamente automaticamente." }
};

const copies: Record<Locale, InteractiveCopy> = { en, es, pt };
export function getInteractiveCopy(locale: Locale): InteractiveCopy { return copies[locale]; }
